version: '3.18'

services:
  sv-dns:
    build:
      dockerfile: docker/coredns.Dockerfile
      context: .
    image: koh/sv-coredns
    container_name: sv-coredns
    restart: on-failure
    networks:
      vps-network:
      dns-network:
        ipv4_address: 10.5.0.5
      mail-network:
      sv-network:
    deploy:
      resources:
        limits:
          cpus: 0.8
          memory: 64M

  sv-db:
    env_file: env/mariadb.env
    profiles:
      - dev
    build:
      dockerfile: docker/db.Dockerfile
      context: .
    image: koh/db-hub
    container_name: sv-database
    volumes:
      - .docker_cache/db_data:/var/lib/mysql
    networks:
      - kafka-network
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 128M

  sv-zoo:
    env_file: env/zoo.env
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: sv-zoo
#    ports:
#      - "2181:2181"
    networks:
      - kafka-network
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 128M

  sv-kafkacluster1:
    env_file: env/kafkacluster1.env
    image: confluentinc/cp-kafka:7.3.2
    container_name: sv-kafkacluster1
#    expose:
#      - "9092:9092"
#      - "29092:29092"
#      - "9999:9999"
    depends_on:
      - sv-zoo
    networks:
      - kafka-network
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M

  sv-mailserver:
    env_file: env/mailserver.env
    build:
      dockerfile: docker/mailserver.Dockerfile
      context: .
    image: koh/mailserver
    container_name: sv-mailserver
    hostname: mail
    domainname: chastnyy.online
    ports:
      - "25:25"    # SMTP
      - "587:587"  # Submission
      - "143:143"  # IMAP
      - "993:993"  # IMAPS
    volumes:
#      - ./.docker_cache/dms/mail-data/:/var/mail/
#      - ./.docker_cache/dms/mail-state/:/var/mail-state/
#      - ./.docker_cache/dms/mail-logs/:/var/log/mail/
      - ./configs/mailserver/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt/:/etc/letsencrypt/ # Mount Let's Encrypt certificates
    profiles:
      - mail-dev
    restart: always
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    networks:
      - mail-network
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 256M

networks:
  vps-network:
    external: true

  dns-network:
    external: true

  mail-network:
    external: true

  kafka-network:
    external: true

  sv-network:
    external: true
